defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}
_target_: agent.eval.eval_reflow_agent.EvalReFlowAgent

name: ${env_name}_eval_reflow_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path:
# ${oc.env:REINFLOW_LOG_DIR}/gym/finetune/ant-medium-expert-v0_ppo_reflow_mlp_ta4_td20/2025-01-31_11-18-02_42/checkpoint/best.pt
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env_name}/normalization.npz
seed: 42
device: cuda:2
sim_device: cuda:0

env_name: ant-medium-expert-v0
obs_dim: 111
action_dim: 8
denoising_steps: 20
denoising_step_list: [4] #20
cond_steps: 1
horizon_steps: 4
act_steps: 4
load_ema: True


batch_size: 128

n_steps: 1000
render_num: 0

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3  # success rate not relevant for gym tasks
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true

model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    # network_path: ${base_policy_path}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16 # 128 
    mlp_dims: [512, 512, 512] # [512, 1024, 512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false #true
    residual_style: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}